# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 313b59c3f8180c35ae9c6116501b28530eb8c2c7646717e8196d7c8b29a98bc0d4d3b00cdcc52b3a27e770f954e0399be8eeedcbbf306057f3ba396abe0c5f61

test:
  secret_key_base: b31775ecf8fe8831d259f119773deb2d95439f03139c8b5f07e0ed101591c4be13a4e68e3f1103682cccf65521d342880ee771f7c2c8ef8e74e5367a1ec95dfb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
